version: '3.8'

services:
  frontend:
    build:
      context: ./podcraft
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/audio_storage:/app/audio_storage
      - ./server/transcripts:/app/transcripts
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVEN_API_KEY=${ELEVEN_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 